name: push

on: 
  push:
  delete:
  create:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Dispatcher
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          token: ${{ secrets.TOKEN }}
          repo: A-JiuA/Hexo
          workflow: build.yml
