name: push

on: 
  push:
  delete:
  create:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Dispatcher
        uses: Codex-/return-dispatch@v1.10.0
        with:
          token: ${{ secrets.TOKEN }}
          ref: main
          repo: Hexo
          owner: A-JiuA
          workflow: build.yml
